version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    allow:
      - dependency-type: "production"
    reviewers:
      - "UserLeap/sdk-new-initiatives"
