

source 'https://github.com/CocoaPods/Specs.git'
install! 'cocoapods', :deterministic_uuids => false

target 'ReactNativeTestApp' do
  require_relative '../node_modules/react-native/scripts/react_native_pods'
  platform :ios, '15.1'
  use_react_native!(
    :path => '../node_modules/react-native',
    :hermes_enabled => true,
    :fabric_enabled => false,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  config = use_native_modules!

  target 'ReactNativeTestAppTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    react_native_post_install(installer)
    installer.pods_project.targets.each do |target|
      if target.name == 'fmt'
        target.build_configurations.each do |config|
          config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++17'
        end
      end
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.1'
      end
      target.build_configurations.each do |config|
        flags = config.build_settings['OTHER_CPLUSPLUSFLAGS'] || ['$(inherited)']
        flags = flags.split(' ') if flags.is_a?(String)
        flags << '-DFOLLY_CFG_NO_COROUTINES=1'
        config.build_settings['OTHER_CPLUSPLUSFLAGS'] = flags
      end
    end
  end
end
